apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service
  template:
    metadata:
      labels:
        app: genai-service
    spec:
      containers:
      - name: genai-service
        image: devops8080/spring-petclinic-genai-service:latest
        resources:
          limits:
            memory: "512Mi"
        ports:
        - containerPort: 8084
        env:
        - name: OPENAI_API_KEY
          value: "your-openai-key-here"  # Replace with your key
        - name: AZURE_OPENAI_KEY
          value: "your-azure-key-here"  # Replace or leave empty
        - name: AZURE_OPENAI_ENDPOINT
          value: "https://your-resource.openai.azure.com"  # Replace or leave empty
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
spec:
  selector:
    app: genai-service
  ports:
  - port: 8084
    targetPort: 8084
  type: ClusterIP