apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-server
  template:
    metadata:
      labels:
        app: grafana-server
    spec:
      containers:
      - name: grafana-server
        image: devops8080/spring-petclinic-grafana-server:latest
        resources:
          limits:
            memory: "256Mi"
        ports:
        - containerPort: 3030
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-server
spec:
  selector:
    app: grafana-server
  ports:
  - port: 3030
    targetPort: 3030
  type: LoadBalancer