apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      containers:
      - name: prometheus-server
        image: devops8080/spring-petclinic-prometheus-server:latest
        resources:
          limits:
            memory: "256Mi"
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-server
spec:
  selector:
    app: prometheus-server
  ports:
  - port: 9091
    targetPort: 9090
  type: LoadBalancer